apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: mutual_fund_nodes-eks-node-group-98b25403beca7b5486ac4894e5
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: mutualfund-app-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: mutualfund-app-eks
  amiSelectorTerms:
    - alias: al2023@latest
