apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: mutual_fund_nodes-eks-node-group-5efce52f0131ec3f8aa4bcc2d7
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: mutualfund-app-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: mutualfund-app-eks
  amiSelectorTerms:
    - alias: al2023@latest
