apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: mfapp
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.1.2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
