apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: fund-updated
  labels:
    strimzi.io/cluster: mfapp
spec:
  topicName: fund.updated
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    cleanup.policy: delete
