name: "Terraform CI"

on:
    push:
        paths:
            - "vpc/*.tf"
            - ".github/workflows/**"
    pull_request:
        branches:
            - main
        paths:
            - "vpc/*.tf"
            - ".github/workflows/**"

    workflow_dispatch:

permissions:
    id-token: write # generates a temp ID, later used for OIDC, assumes AWS role
    contents: read # reads the repo, no writes
    pull-requests: write # writesd only on the PR

jobs:
    terraform-plan:
        name: "Terraform Validate & Plan"
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./vpc

        env:
            AWS_REGION: "us-east-1"
            TF_LOG: INFO

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "AWS creds - OIDC"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::514005485562:role/GitHubActionsTerraformRole
                  aws-region: ${{ env.AWS_REGION }}

            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.11.0"

            - name: "Terraform init"
              id: init
              run: terraform init

            - name: "Terraform Plan"
              id: plan
              run: terraform plan -input=false -no-color -out=tfplan

            - name: "terraform plan upload"
              uses: actions/upload-artifact@v4
              with:
                  name: tfplan
                  path: tfplan
                  retention-days: 1

    terraform-apply:
        name: "Terraform Apply"
        runs-on: ubuntu-latest
        needs: terraform-plan
        # Only run apply if on main branch or manually dispatched
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        environment: production

        env:
            AWS_REGION: "us-east-1"
            TF_LOG: INFO

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "AWS creds - OIDC"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::514005485562:role/GitHubActionsTerraformRole
                  aws-region: ${{ env.AWS_REGION }}

            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.11.0"

            - name: "Download Terraform Plan"
              uses: actions/download-artifact@v4
              with:
                  name: tfplan

            - name: "Terraform init"
              id: init
              run: terraform init

            - name: "Terraform Apply"
              run: terraform apply -input=false -no-color tfplan
